name: 'Hello World'
description: 'des'
inputs:
  who-to-great:
    description: 'user'
    required: true
    default: 'starain'
outputs:
  time:
    description: 'current time'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{inputs.who-to-great}}
  
